# Generated by Django 3.2.4 on 2021-06-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clien',
            new_name='Client',
        ),
    ]
