# Generated by Django 3.2.4 on 2021-06-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_clien_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
